export const ADD_MOVIE = 'ADD_MOVIE';
export const START_LOADING_MOVIES = 'START_LOADING_MOVIE';
export const SUCCESSFULLY_LOADED_MOVIES = 'SUCCESSFULLY_LOAD_MOVIES';
export const FAILED_LOADING_MOVIES = 'FAILED_LOADING_MOVIES';


