


export const START_LOADING_MOVIES = 'START_LOADING_MOVIE';
export const SUCCESSFULLY_LOADED_MOVIES = 'SUCCESSFULLY_LOAD_MOVIES';
export const SUCCESSFULLY_LOADED_MOVIE_REVIEWS = 'SUCCESSFULLY_LOAD_MOVIES_REVIEWS';
export const FAILED_LOADING_MOVIES = 'FAILED_LOADING_MOVIES';
export const START_LOADING_MOVIE = 'START_LOADING_MOVIE';
export const SUCCESSFULLY_CREATED_MOVIE = "SUCCESSFULLY_CREATED_MOVIE";



export const SUCCESSFULLY_CREATED_REVIEW = 'SUCCESSFULLY_CREATED_REVIEW';



